# Generated by Django 3.1.4 on 2021-02-11 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(default=100, max_length=100, verbose_name='فضا')),
                ('used_space', models.CharField(default=0, max_length=100, verbose_name='فضای استفاده شده')),
                ('used_percent', models.CharField(default=0, max_length=10, verbose_name='درصد استفاده شده')),
            ],
            options={
                'verbose_name': 'ابر',
                'verbose_name_plural': 'ابر\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='آواتار')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('public_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='پست الکترونیک')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('year_of_born', models.CharField(blank=True, choices=[('1330', '1330'), ('1331', '1331'), ('1332', '1332'), ('1333', '1333'), ('1334', '1334'), ('1335', '1335'), ('1336', '1336'), ('1337', '1337'), ('1338', '1338'), ('1339', '1339'), ('1340', '1340'), ('1341', '1341'), ('1342', '1342'), ('1343', '1343'), ('1344', '1344'), ('1345', '1345'), ('1346', '1346'), ('1347', '1347'), ('1348', '1348'), ('1349', '1349'), ('1350', '1350'), ('1351', '1351'), ('1352', '1352'), ('1353', '1353'), ('1354', '1354'), ('1355', '1355'), ('1356', '1356'), ('1357', '1357'), ('1358', '1358'), ('1359', '1359'), ('1360', '1360'), ('1361', '1361'), ('1362', '1362'), ('1363', '1363'), ('1364', '1364'), ('1365', '1365'), ('1366', '1366'), ('1367', '1367'), ('1368', '1368'), ('1369', '1369'), ('1370', '1370'), ('1371', '1371'), ('1372', '1372'), ('1373', '1373'), ('1374', '1374'), ('1375', '1375'), ('1376', '1376'), ('1377', '1377'), ('1378', '1378'), ('1379', '1379'), ('1380', '1380'), ('1381', '1381'), ('1382', '1382'), ('1383', '1383'), ('1384', '1384'), ('1385', '1385'), ('1386', '1386'), ('1387', '1387'), ('1388', '1388'), ('1389', '1389'), ('1390', '1390'), ('1391', '1391'), ('1392', '1392'), ('1393', '1393'), ('1394', '1394')], max_length=4, null=True, verbose_name='سال تولد')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='جنسیت')),
                ('join_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان عضویت')),
                ('work', models.CharField(blank=True, max_length=50, null=True, verbose_name='تخصص')),
                ('rezome', models.TextField(blank=True, default='', null=True, verbose_name='رزومه')),
                ('len_following', models.CharField(default=0, max_length=10, verbose_name='تعداد دنبال شوندگان')),
                ('len_followers', models.CharField(default=0, max_length=10, verbose_name='تعداد دنبال کنندگان')),
                ('github', models.URLField(blank=True, null=True, verbose_name='گیت\u200cهاب')),
                ('gitlab', models.URLField(blank=True, null=True, verbose_name='گیت\u200cلب')),
                ('stackowerflow', models.URLField(blank=True, null=True, verbose_name='استک اورفلو')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('dev', models.URLField(blank=True, null=True, verbose_name='جامعه دِو')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('followers', models.ManyToManyField(blank=True, related_name='folllowers', to='main.Person', verbose_name='دنبال کنندگان')),
                ('following', models.ManyToManyField(blank=True, to='main.Person', verbose_name='دنبال شوندگان')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('cover', models.CharField(blank=True, max_length=1000, null=True, verbose_name='کاور')),
                ('category', models.CharField(max_length=50, null=True, verbose_name='دسته بندی')),
                ('short_description', models.TextField(blank=True, max_length=156, null=True, verbose_name='توضیح کوتاه')),
                ('publish_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('comments', models.CharField(default='0', max_length=10, verbose_name='تعداد نظر')),
                ('likes', models.CharField(default='0', max_length=10, verbose_name='تعداد لایک')),
                ('views', models.CharField(default='0', max_length=10, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'مطالب',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.Post', verbose_name='لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.Skill', verbose_name='مهارت\u200cها'),
        ),
        migrations.AddField(
            model_name='person',
            name='viewed_posts',
            field=models.ManyToManyField(blank=True, related_name='views_post', to='main.Post', verbose_name='مطالب مشاهده شده'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('notif_type', models.CharField(default=None, max_length=10, null=True, verbose_name='نوع')),
                ('done', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('givver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person', verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='images/', verbose_name='فایل')),
                ('cloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cloud', verbose_name='ابر')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن')),
                ('submit_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person', verbose_name='نویسنده')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post', verbose_name='مکان')),
                ('replays', models.ManyToManyField(blank=True, to='main.Comment', verbose_name='پاسخ\u200cها')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.AddField(
            model_name='cloud',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person', verbose_name='صاحب'),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='نوع')),
                ('available_views', models.CharField(default=100, max_length=10, verbose_name='بازدید باقی مانده')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post', verbose_name='مطلب')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
    ]
