# Generated by Django 3.1.4 on 2021-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210304_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='rdh'),
            preserve_default=False,
        ),
    ]
