# Generated by Django 3.1.4 on 2021-03-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210304_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.person', verbose_name='صاحب'),
        ),
    ]
