# Generated by Django 3.1.7 on 2021-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210304_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='person',
            name='matrix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ماتریکس'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توییتر'),
        ),
        migrations.AddField(
            model_name='person',
            name='virgool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ویرگول'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='space',
            field=models.CharField(default=25, max_length=25, verbose_name='فضا'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='used_percent',
            field=models.CharField(default=0, max_length=5, verbose_name='درصد استفاده شده'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='used_space',
            field=models.CharField(default=0, max_length=25, verbose_name='فضای استفاده شده'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dev',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دِو'),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='گیت\u200cهاب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gitlab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='گیت\u200cلب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='person',
            name='public_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رایانامه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stackowerflow',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استک\u200cاورفلو'),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(null=True, verbose_name='تارنما'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_born',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='سال تولد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
