# Generated by Django 3.1.7 on 2021-07-02 08:34

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210623_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='stackowerflow',
            new_name='stackoverflow',
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 2, 13, 4, 48, 466825), verbose_name='زمان پایان'),
        ),
    ]
