# Generated by Django 3.1.7 on 2021-07-04 09:06

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210704_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 4, 13, 36, 47, 792402), verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='main.Person', verbose_name='پسندیدگان'),
        ),
    ]
