# Generated by Django 3.1.7 on 2021-07-07 07:25

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210707_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 7, 11, 55, 53, 356908), verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='person',
            name='virgool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ویرگول'),
        ),
    ]
