# Generated by Django 3.1.7 on 2021-07-09 06:51

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210709_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='givver',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 9, 11, 21, 26, 920620), verbose_name='زمان پایان'),
        ),
    ]
