# Generated by Django 3.1.7 on 2021-07-18 09:09

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210709_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replays',
        ),
        migrations.AddField(
            model_name='comment',
            name='replys',
            field=models.ManyToManyField(blank=True, to='main.Comment', verbose_name='پاسخ\u200cها'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 18, 13, 38, 49, 721036), verbose_name='زمان پایان'),
        ),
    ]
